# fly.toml app configuration file generated for war-room-kwasikontor on 2026-04-27T22:02:19-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'war-room-kwasikontor'
primary_region = 'lhr'

[build]

[env]
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
